# Generated by Django 5.2.3 on 2025-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPotensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rincian', models.TextField()),
                ('objek', models.CharField()),
                ('jenis', models.CharField()),
                ('provinsi', models.CharField()),
                ('daerah', models.CharField()),
                ('kategori_apbd', models.CharField()),
                ('tahun', models.IntegerField()),
                ('nilai', models.BigIntegerField()),
            ],
            options={
                'db_table': 'data_potensi',
            },
        ),
        migrations.CreateModel(
            name='LogUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('aksi', models.CharField(max_length=100)),
                ('detail_aksi', models.TextField()),
            ],
            options={
                'db_table': 'log_update',
            },
        ),
        migrations.CreateModel(
            name='ProdukHukum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('level1', models.CharField(blank=True, max_length=255, null=True)),
                ('level2', models.CharField(blank=True, max_length=255, null=True)),
                ('level3', models.CharField(blank=True, max_length=255, null=True)),
                ('level4', models.CharField(blank=True, max_length=255, null=True)),
                ('aturan1', models.TextField(blank=True, null=True)),
                ('remark1', models.TextField(blank=True, null=True)),
                ('link1', models.URLField(blank=True, null=True)),
                ('status1', models.URLField(blank=True, null=True)),
                ('aturan2', models.TextField(blank=True, null=True)),
                ('remark2', models.TextField(blank=True, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('status2', models.URLField(blank=True, null=True)),
                ('aturan3', models.TextField(blank=True, null=True)),
                ('remark3', models.TextField(blank=True, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
                ('status3', models.URLField(blank=True, null=True)),
                ('aturan4', models.TextField(blank=True, null=True)),
                ('remark4', models.TextField(blank=True, null=True)),
                ('link4', models.URLField(blank=True, null=True)),
                ('status4', models.URLField(blank=True, null=True)),
                ('aturan5', models.TextField(blank=True, null=True)),
                ('remark5', models.TextField(blank=True, null=True)),
                ('link5', models.URLField(blank=True, null=True)),
                ('status5', models.URLField(blank=True, null=True)),
                ('aturan6', models.TextField(blank=True, null=True)),
                ('remark6', models.TextField(blank=True, null=True)),
                ('link6', models.URLField(blank=True, null=True)),
                ('status6', models.URLField(blank=True, null=True)),
                ('aturan7', models.TextField(blank=True, null=True)),
                ('remark7', models.TextField(blank=True, null=True)),
                ('link7', models.URLField(blank=True, null=True)),
                ('status7', models.URLField(blank=True, null=True)),
                ('aturan8', models.TextField(blank=True, null=True)),
                ('remark8', models.TextField(blank=True, null=True)),
                ('link8', models.URLField(blank=True, null=True)),
                ('status8', models.URLField(blank=True, null=True)),
                ('aturan9', models.TextField(blank=True, null=True)),
                ('remark9', models.TextField(blank=True, null=True)),
                ('link9', models.URLField(blank=True, null=True)),
                ('status9', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produk_hukum',
            },
        ),
    ]
